### ISSUE TITLE
It keeps Reloading

### ISSUE THREAD

**Issue by hollabck** [smd111/Gearswap#5]
Good Morning,
So I went and updated everything and was using a basic (pld) file to test out if the Trizek ring crash has been fixed, but the GS keeps reloading and reorganizing over and over.  I literally just downloaded and added everything per the instructions and did not modify anything.

**Comment by smd111** [comment]
give me a min ill check it out
also when does it happen it should happen every zone and every time you log on(tho i found a way to only do it when you log on)

**Comment by smd111** [comment]
i see whats going on you loging in while your char is in the mog house give me 10 mins to fix this

**Comment by smd111** [comment]
i just pushed a fix

if you log in when your in the mog house it will reload when you zone out after the server updates your items again

it also reloads once after you first log in if your not in your mog house 

this should only happen once for log in and job changes this is because the menu has to be rebuilt after the server updates your items there is nothing i can do about it unless byrth puts the user file load after the item update's are done from the server
